package com.linkpets.dao;

import com.linkpets.model.ShopImg;

import java.util.List;

import org.apache.ibatis.annotations.*;

public interface ShopImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_img
     *
     * @mbg.generated Tue Sep 24 17:39:06 GMT+08:00 2019
     */
    @Delete({
        "delete from shop_img",
        "where pk_id = #{pkId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_img
     *
     * @mbg.generated Tue Sep 24 17:39:06 GMT+08:00 2019
     */
    @Insert({
        "insert into shop_img (pk_id, shop_id, ",
        "img_name, img_url, ",
        "del_flag)",
        "values (#{pkId,jdbcType=INTEGER}, #{shopId,jdbcType=VARCHAR}, ",
        "#{imgName,jdbcType=VARCHAR}, #{imgUrl,jdbcType=VARCHAR}, ",
        "#{delFlag,jdbcType=VARCHAR})"
    })
    int insert(ShopImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_img
     *
     * @mbg.generated Tue Sep 24 17:39:06 GMT+08:00 2019
     */
    int insertSelective(ShopImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_img
     *
     * @mbg.generated Tue Sep 24 17:39:06 GMT+08:00 2019
     */
    @Select({
        "select",
        "pk_id, shop_id, img_name, img_url, del_flag",
        "from shop_img",
        "where pk_id = #{pkId,jdbcType=INTEGER}"
    })
    @ResultMap("com.linkpets.dao.ShopImgMapper.BaseResultMap")
    ShopImg selectByPrimaryKey(Integer pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_img
     *
     * @mbg.generated Tue Sep 24 17:39:06 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(ShopImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_img
     *
     * @mbg.generated Tue Sep 24 17:39:06 GMT+08:00 2019
     */
    @Update({
        "update shop_img",
        "set shop_id = #{shopId,jdbcType=VARCHAR},",
          "img_name = #{imgName,jdbcType=VARCHAR},",
          "img_url = #{imgUrl,jdbcType=VARCHAR},",
          "del_flag = #{delFlag,jdbcType=VARCHAR}",
        "where pk_id = #{pkId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ShopImg record);

    @Update({
        "update shop_img",
        "set del_flag = '0'",
        "where del_flag = '1' and shop_id = #{shopId,jdbcType=VARCHAR}"
    })
	void delImg(String shopId);

    /*@Select({
        "select",
        "pk_id as pkId, shop_id as shopId, img_name as imgName, img_url as imgUrl",
        "from shop_img",
        "where shop_id = #{shoId,jdbcType=VARCHAR}"
    })
    @ResultType(JSONObject.class)
    JSONObject getImgList(String shopId);*/
    
    @Select({
        "select",
        "pk_id, shop_id, img_name, img_url, del_flag",
        "from shop_img",
        "where shop_id = #{shoId,jdbcType=VARCHAR} and del_flag='0'"
	})
	@ResultMap("com.linkpets.dao.ShopImgMapper.BaseResultMap")
	List<ShopImg> getImgList(String shopId);
}
