package com.linkpets.dao;

import com.linkpets.model.SysLog;
import com.linkpets.model.SysLogWithBLOBs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SysLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    @Delete({
        "delete from sys_log",
        "where log_id = #{logId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    @Insert({
        "insert into sys_log (log_id, request_by, ",
        "request_ip, request_time, ",
        "request_url, request_method, ",
        "response_code, request_params, ",
        "request_body, response_msg, ",
        "response_data)",
        "values (#{logId,jdbcType=INTEGER}, #{requestBy,jdbcType=VARCHAR}, ",
        "#{requestIp,jdbcType=VARCHAR}, #{requestTime,jdbcType=TIMESTAMP}, ",
        "#{requestUrl,jdbcType=VARCHAR}, #{requestMethod,jdbcType=VARCHAR}, ",
        "#{responseCode,jdbcType=VARCHAR}, #{requestParams,jdbcType=LONGVARCHAR}, ",
        "#{requestBody,jdbcType=LONGVARCHAR}, #{responseMsg,jdbcType=LONGVARCHAR}, ",
        "#{responseData,jdbcType=LONGVARCHAR})"
    })
    int insert(SysLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    int insertSelective(SysLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    @Select({
        "select",
        "log_id, request_by, request_ip, request_time, request_url, request_method, response_code, ",
        "request_params, request_body, response_msg, response_data",
        "from sys_log",
        "where log_id = #{logId,jdbcType=INTEGER}"
    })
    @ResultMap("com.linkpets.dao.SysLogMapper.ResultMapWithBLOBs")
    SysLogWithBLOBs selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(SysLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    @Update({
        "update sys_log",
        "set request_by = #{requestBy,jdbcType=VARCHAR},",
          "request_ip = #{requestIp,jdbcType=VARCHAR},",
          "request_time = #{requestTime,jdbcType=TIMESTAMP},",
          "request_url = #{requestUrl,jdbcType=VARCHAR},",
          "request_method = #{requestMethod,jdbcType=VARCHAR},",
          "response_code = #{responseCode,jdbcType=VARCHAR},",
          "request_params = #{requestParams,jdbcType=LONGVARCHAR},",
          "request_body = #{requestBody,jdbcType=LONGVARCHAR},",
          "response_msg = #{responseMsg,jdbcType=LONGVARCHAR},",
          "response_data = #{responseData,jdbcType=LONGVARCHAR}",
        "where log_id = #{logId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(SysLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    @Update({
        "update sys_log",
        "set request_by = #{requestBy,jdbcType=VARCHAR},",
          "request_ip = #{requestIp,jdbcType=VARCHAR},",
          "request_time = #{requestTime,jdbcType=TIMESTAMP},",
          "request_url = #{requestUrl,jdbcType=VARCHAR},",
          "request_method = #{requestMethod,jdbcType=VARCHAR},",
          "response_code = #{responseCode,jdbcType=VARCHAR}",
        "where log_id = #{logId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SysLog record);
}