package com.linkpets.model;

public class ActivityCommodityKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_commodity.activity_id
     *
     * @mbg.generated Wed Oct 09 18:42:14 GMT+08:00 2019
     */
    private String activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_commodity.commodity_id
     *
     * @mbg.generated Wed Oct 09 18:42:14 GMT+08:00 2019
     */
    private String commodityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_commodity.activity_id
     *
     * @return the value of activity_commodity.activity_id
     *
     * @mbg.generated Wed Oct 09 18:42:14 GMT+08:00 2019
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_commodity.activity_id
     *
     * @param activityId the value for activity_commodity.activity_id
     *
     * @mbg.generated Wed Oct 09 18:42:14 GMT+08:00 2019
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_commodity.commodity_id
     *
     * @return the value of activity_commodity.commodity_id
     *
     * @mbg.generated Wed Oct 09 18:42:14 GMT+08:00 2019
     */
    public String getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_commodity.commodity_id
     *
     * @param commodityId the value for activity_commodity.commodity_id
     *
     * @mbg.generated Wed Oct 09 18:42:14 GMT+08:00 2019
     */
    public void setCommodityId(String commodityId) {
        this.commodityId = commodityId;
    }
}