package com.linkpets.model;

import java.util.Date;

public class ActivityInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.activity_id
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    private String activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.activity_name
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    private String activityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.activity_status
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    private String activityStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.shop_id
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.start_time
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.end_time
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.remark
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.create_by
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.create_date
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.del_flag
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.activity_id
     *
     * @return the value of activity_info.activity_id
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.activity_id
     *
     * @param activityId the value for activity_info.activity_id
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.activity_name
     *
     * @return the value of activity_info.activity_name
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.activity_name
     *
     * @param activityName the value for activity_info.activity_name
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.activity_status
     *
     * @return the value of activity_info.activity_status
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    public String getActivityStatus() {
        return activityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.activity_status
     *
     * @param activityStatus the value for activity_info.activity_status
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    public void setActivityStatus(String activityStatus) {
        this.activityStatus = activityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.shop_id
     *
     * @return the value of activity_info.shop_id
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.shop_id
     *
     * @param shopId the value for activity_info.shop_id
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    public void setShopId(String shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.start_time
     *
     * @return the value of activity_info.start_time
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.start_time
     *
     * @param startTime the value for activity_info.start_time
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.end_time
     *
     * @return the value of activity_info.end_time
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.end_time
     *
     * @param endTime the value for activity_info.end_time
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.remark
     *
     * @return the value of activity_info.remark
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.remark
     *
     * @param remark the value for activity_info.remark
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.create_by
     *
     * @return the value of activity_info.create_by
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.create_by
     *
     * @param createBy the value for activity_info.create_by
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.create_date
     *
     * @return the value of activity_info.create_date
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.create_date
     *
     * @param createDate the value for activity_info.create_date
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.del_flag
     *
     * @return the value of activity_info.del_flag
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.del_flag
     *
     * @param delFlag the value for activity_info.del_flag
     *
     * @mbg.generated Wed Oct 09 18:40:51 GMT+08:00 2019
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}