package com.linkpets.model;

import java.math.BigDecimal;

public class ActivityCommodity extends ActivityCommodityKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_commodity.activity_price
     *
     * @mbg.generated Wed Oct 09 18:42:14 GMT+08:00 2019
     */
    private BigDecimal activityPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_commodity.total_limit
     *
     * @mbg.generated Wed Oct 09 18:42:14 GMT+08:00 2019
     */
    private Integer totalLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_commodity.per_limit
     *
     * @mbg.generated Wed Oct 09 18:42:14 GMT+08:00 2019
     */
    private Integer perLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_commodity.activity_inventory
     *
     * @mbg.generated Wed Oct 09 18:42:14 GMT+08:00 2019
     */
    private Integer activityInventory;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_commodity.activity_price
     *
     * @return the value of activity_commodity.activity_price
     *
     * @mbg.generated Wed Oct 09 18:42:14 GMT+08:00 2019
     */
    public BigDecimal getActivityPrice() {
        return activityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_commodity.activity_price
     *
     * @param activityPrice the value for activity_commodity.activity_price
     *
     * @mbg.generated Wed Oct 09 18:42:14 GMT+08:00 2019
     */
    public void setActivityPrice(BigDecimal activityPrice) {
        this.activityPrice = activityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_commodity.total_limit
     *
     * @return the value of activity_commodity.total_limit
     *
     * @mbg.generated Wed Oct 09 18:42:14 GMT+08:00 2019
     */
    public Integer getTotalLimit() {
        return totalLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_commodity.total_limit
     *
     * @param totalLimit the value for activity_commodity.total_limit
     *
     * @mbg.generated Wed Oct 09 18:42:14 GMT+08:00 2019
     */
    public void setTotalLimit(Integer totalLimit) {
        this.totalLimit = totalLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_commodity.per_limit
     *
     * @return the value of activity_commodity.per_limit
     *
     * @mbg.generated Wed Oct 09 18:42:14 GMT+08:00 2019
     */
    public Integer getPerLimit() {
        return perLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_commodity.per_limit
     *
     * @param perLimit the value for activity_commodity.per_limit
     *
     * @mbg.generated Wed Oct 09 18:42:14 GMT+08:00 2019
     */
    public void setPerLimit(Integer perLimit) {
        this.perLimit = perLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_commodity.activity_inventory
     *
     * @return the value of activity_commodity.activity_inventory
     *
     * @mbg.generated Wed Oct 09 18:42:14 GMT+08:00 2019
     */
    public Integer getActivityInventory() {
        return activityInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_commodity.activity_inventory
     *
     * @param activityInventory the value for activity_commodity.activity_inventory
     *
     * @mbg.generated Wed Oct 09 18:42:14 GMT+08:00 2019
     */
    public void setActivityInventory(Integer activityInventory) {
        this.activityInventory = activityInventory;
    }
}