package com.linkpets.model;

public class CommodityImg {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity_img.pk_id
	 * @mbg.generated  Tue Oct 08 11:17:45 GMT+08:00 2019
	 */
	private Integer pkId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity_img.commodity_id
	 * @mbg.generated  Tue Oct 08 11:17:45 GMT+08:00 2019
	 */
	private String commodityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity_img.img_name
	 * @mbg.generated  Tue Oct 08 11:17:45 GMT+08:00 2019
	 */
	private String imgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity_img.img_url
	 * @mbg.generated  Tue Oct 08 11:17:45 GMT+08:00 2019
	 */
	private String imgUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity_img.del_flag
	 * @mbg.generated  Tue Oct 08 11:17:45 GMT+08:00 2019
	 */
	private String delFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_img.pk_id
	 * @return  the value of commodity_img.pk_id
	 * @mbg.generated  Tue Oct 08 11:17:45 GMT+08:00 2019
	 */
	public Integer getPkId() {
		return pkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_img.pk_id
	 * @param pkId  the value for commodity_img.pk_id
	 * @mbg.generated  Tue Oct 08 11:17:45 GMT+08:00 2019
	 */
	public void setPkId(Integer pkId) {
		this.pkId = pkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_img.commodity_id
	 * @return  the value of commodity_img.commodity_id
	 * @mbg.generated  Tue Oct 08 11:17:45 GMT+08:00 2019
	 */
	public String getCommodityId() {
		return commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_img.commodity_id
	 * @param commodityId  the value for commodity_img.commodity_id
	 * @mbg.generated  Tue Oct 08 11:17:45 GMT+08:00 2019
	 */
	public void setCommodityId(String commodityId) {
		this.commodityId = commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_img.img_name
	 * @return  the value of commodity_img.img_name
	 * @mbg.generated  Tue Oct 08 11:17:45 GMT+08:00 2019
	 */
	public String getImgName() {
		return imgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_img.img_name
	 * @param imgName  the value for commodity_img.img_name
	 * @mbg.generated  Tue Oct 08 11:17:45 GMT+08:00 2019
	 */
	public void setImgName(String imgName) {
		this.imgName = imgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_img.img_url
	 * @return  the value of commodity_img.img_url
	 * @mbg.generated  Tue Oct 08 11:17:45 GMT+08:00 2019
	 */
	public String getImgUrl() {
		return imgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_img.img_url
	 * @param imgUrl  the value for commodity_img.img_url
	 * @mbg.generated  Tue Oct 08 11:17:45 GMT+08:00 2019
	 */
	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_img.del_flag
	 * @return  the value of commodity_img.del_flag
	 * @mbg.generated  Tue Oct 08 11:17:45 GMT+08:00 2019
	 */
	public String getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_img.del_flag
	 * @param delFlag  the value for commodity_img.del_flag
	 * @mbg.generated  Tue Oct 08 11:17:45 GMT+08:00 2019
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}
}