package com.linkpets.model;

public class MallTest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_test.pk_id
     *
     * @mbg.generated Tue Sep 17 13:44:32 GMT+08:00 2019
     */
    private Integer pkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_test.name
     *
     * @mbg.generated Tue Sep 17 13:44:32 GMT+08:00 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_test.info
     *
     * @mbg.generated Tue Sep 17 13:44:32 GMT+08:00 2019
     */
    private String info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_test.pk_id
     *
     * @return the value of mall_test.pk_id
     *
     * @mbg.generated Tue Sep 17 13:44:32 GMT+08:00 2019
     */
    public Integer getPkId() {
        return pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_test.pk_id
     *
     * @param pkId the value for mall_test.pk_id
     *
     * @mbg.generated Tue Sep 17 13:44:32 GMT+08:00 2019
     */
    public void setPkId(Integer pkId) {
        this.pkId = pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_test.name
     *
     * @return the value of mall_test.name
     *
     * @mbg.generated Tue Sep 17 13:44:32 GMT+08:00 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_test.name
     *
     * @param name the value for mall_test.name
     *
     * @mbg.generated Tue Sep 17 13:44:32 GMT+08:00 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_test.info
     *
     * @return the value of mall_test.info
     *
     * @mbg.generated Tue Sep 17 13:44:32 GMT+08:00 2019
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_test.info
     *
     * @param info the value for mall_test.info
     *
     * @mbg.generated Tue Sep 17 13:44:32 GMT+08:00 2019
     */
    public void setInfo(String info) {
        this.info = info;
    }
}