package com.linkpets.model;

public class ShopImg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_img.pk_id
     *
     * @mbg.generated Tue Sep 24 17:39:06 GMT+08:00 2019
     */
    private Integer pkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_img.shop_id
     *
     * @mbg.generated Tue Sep 24 17:39:06 GMT+08:00 2019
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_img.img_name
     *
     * @mbg.generated Tue Sep 24 17:39:06 GMT+08:00 2019
     */
    private String imgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_img.img_url
     *
     * @mbg.generated Tue Sep 24 17:39:06 GMT+08:00 2019
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_img.del_flag
     *
     * @mbg.generated Tue Sep 24 17:39:06 GMT+08:00 2019
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_img.pk_id
     *
     * @return the value of shop_img.pk_id
     *
     * @mbg.generated Tue Sep 24 17:39:06 GMT+08:00 2019
     */
    public Integer getPkId() {
        return pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_img.pk_id
     *
     * @param pkId the value for shop_img.pk_id
     *
     * @mbg.generated Tue Sep 24 17:39:06 GMT+08:00 2019
     */
    public void setPkId(Integer pkId) {
        this.pkId = pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_img.shop_id
     *
     * @return the value of shop_img.shop_id
     *
     * @mbg.generated Tue Sep 24 17:39:06 GMT+08:00 2019
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_img.shop_id
     *
     * @param shopId the value for shop_img.shop_id
     *
     * @mbg.generated Tue Sep 24 17:39:06 GMT+08:00 2019
     */
    public void setShopId(String shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_img.img_name
     *
     * @return the value of shop_img.img_name
     *
     * @mbg.generated Tue Sep 24 17:39:06 GMT+08:00 2019
     */
    public String getImgName() {
        return imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_img.img_name
     *
     * @param imgName the value for shop_img.img_name
     *
     * @mbg.generated Tue Sep 24 17:39:06 GMT+08:00 2019
     */
    public void setImgName(String imgName) {
        this.imgName = imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_img.img_url
     *
     * @return the value of shop_img.img_url
     *
     * @mbg.generated Tue Sep 24 17:39:06 GMT+08:00 2019
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_img.img_url
     *
     * @param imgUrl the value for shop_img.img_url
     *
     * @mbg.generated Tue Sep 24 17:39:06 GMT+08:00 2019
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_img.del_flag
     *
     * @return the value of shop_img.del_flag
     *
     * @mbg.generated Tue Sep 24 17:39:06 GMT+08:00 2019
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_img.del_flag
     *
     * @param delFlag the value for shop_img.del_flag
     *
     * @mbg.generated Tue Sep 24 17:39:06 GMT+08:00 2019
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}