package com.linkpets.model;

import java.util.Date;

public class SysLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.log_id
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    private Integer logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.request_by
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    private String requestBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.request_ip
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    private String requestIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.request_time
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    private Date requestTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.request_url
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    private String requestUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.request_method
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    private String requestMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.response_code
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    private String responseCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.log_id
     *
     * @return the value of sys_log.log_id
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.log_id
     *
     * @param logId the value for sys_log.log_id
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.request_by
     *
     * @return the value of sys_log.request_by
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public String getRequestBy() {
        return requestBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.request_by
     *
     * @param requestBy the value for sys_log.request_by
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public void setRequestBy(String requestBy) {
        this.requestBy = requestBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.request_ip
     *
     * @return the value of sys_log.request_ip
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public String getRequestIp() {
        return requestIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.request_ip
     *
     * @param requestIp the value for sys_log.request_ip
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.request_time
     *
     * @return the value of sys_log.request_time
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public Date getRequestTime() {
        return requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.request_time
     *
     * @param requestTime the value for sys_log.request_time
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public void setRequestTime(Date requestTime) {
        this.requestTime = requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.request_url
     *
     * @return the value of sys_log.request_url
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public String getRequestUrl() {
        return requestUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.request_url
     *
     * @param requestUrl the value for sys_log.request_url
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.request_method
     *
     * @return the value of sys_log.request_method
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public String getRequestMethod() {
        return requestMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.request_method
     *
     * @param requestMethod the value for sys_log.request_method
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public void setRequestMethod(String requestMethod) {
        this.requestMethod = requestMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.response_code
     *
     * @return the value of sys_log.response_code
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public String getResponseCode() {
        return responseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.response_code
     *
     * @param responseCode the value for sys_log.response_code
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public void setResponseCode(String responseCode) {
        this.responseCode = responseCode;
    }
}