package com.linkpets.model;

public class SysLogWithBLOBs extends SysLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.request_params
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    private String requestParams;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.request_body
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    private String requestBody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.response_msg
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    private String responseMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.response_data
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    private String responseData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.request_params
     *
     * @return the value of sys_log.request_params
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public String getRequestParams() {
        return requestParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.request_params
     *
     * @param requestParams the value for sys_log.request_params
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public void setRequestParams(String requestParams) {
        this.requestParams = requestParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.request_body
     *
     * @return the value of sys_log.request_body
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public String getRequestBody() {
        return requestBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.request_body
     *
     * @param requestBody the value for sys_log.request_body
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public void setRequestBody(String requestBody) {
        this.requestBody = requestBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.response_msg
     *
     * @return the value of sys_log.response_msg
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public String getResponseMsg() {
        return responseMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.response_msg
     *
     * @param responseMsg the value for sys_log.response_msg
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public void setResponseMsg(String responseMsg) {
        this.responseMsg = responseMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.response_data
     *
     * @return the value of sys_log.response_data
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public String getResponseData() {
        return responseData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.response_data
     *
     * @param responseData the value for sys_log.response_data
     *
     * @mbg.generated Tue Sep 17 16:55:16 GMT+08:00 2019
     */
    public void setResponseData(String responseData) {
        this.responseData = responseData;
    }
}